
# Key research questions 

why mass transportation is public good

history and nature of public transporation in Dhaka, Bangldesh 

consequences of competition in public transporation

Forms of Public Intervention 

International best practices on public transportation management 

Employment structure

# Current state 

## Trips 

A project titled "Dhaka Urban Transport Network Development" completed two surveys in 2009 and 2014 with the support of Japan International Cooperation Agency (JICA). In Dhaka, every day 33 million trips are made. Of this 72 percent are made in Buses. Another 15.4 percent are made in autorickshaw. Therefore, close to 90 percent of the trips are covered by bus and autorickshaw. 

## Fitness 

According to Bangladesh Road Transportation Authority(BRTA)[@anwar_palo_respite_2018], there are two hundred and 16 thousand cars which are without fitness. There are two aspects of fitness. One is external and another is internal or technical. To provide fitness, BRTA is required to consider 60 different types of issues. Acording to experts, let alone technical side, if we just consider external factors, 80-90 percent of Bus and Minibus is unfit to move around.

From [@anwar_palo_words_2018] After assuming office in 2009, the Bangladesh Awami League (AL)-led government announced that buses older than 20 years would be shortly withdrawn. In 2011, Obaidul Quader, also the president of road transport advisory council, took office of the road transport and bridges ministry.

Quader, after one year of taking office, came up with an announcement to withdraw all unfit vehicles. He made the same announcement in a meeting of the road transport advisory council in June of the following year, also the last year of this government's previous tenure.

Sometime close to the end of the tenure, minister Quader said, "We cannot do everything now even if we want to."

The AL came to power again after the 5 January elections in 2014 and Quader was handed over the responsibilities of the same ministry. Then, once again he made the announcement in a programme to withdraw unfit vehicles to ease traffic congestion in the Dhaka airport area. An 11-member taskforce, headed by the then chairman of the Bangladesh Road Transport Authority (BRTA), was also formed.


## No. of buses

Over the years number of buses are decereasing. At 2015, bus numbers were reduced to 4500. This situation is quite strange. The factors behind this lower buses is lower profits, uncertainty on political unrest, hooliganism, etc. 

Everyday, around 10 thousand buses are entering our city. 
Over the years, no. of buses are getting reduced. Bus company manufacturers and sellers might be an interested part to all this. 

## How other countries solved the problem

what was the experience of these following cities? 

Dhaka, Kolkata, Bombay, Delhi, Karachi what is their experience? 


## Planning

Who is planning for whom? How the planning is done? Why it is not done? 
